#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="XIUGAR")]
	public partial class PaslumBaseDatoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttblAlmacen(tblAlmacen instance);
    partial void UpdatetblAlmacen(tblAlmacen instance);
    partial void DeletetblAlmacen(tblAlmacen instance);
    partial void InserttblCliente(tblCliente instance);
    partial void UpdatetblCliente(tblCliente instance);
    partial void DeletetblCliente(tblCliente instance);
    partial void InserttblDireccion(tblDireccion instance);
    partial void UpdatetblDireccion(tblDireccion instance);
    partial void DeletetblDireccion(tblDireccion instance);
    partial void InserttblEmpleado(tblEmpleado instance);
    partial void UpdatetblEmpleado(tblEmpleado instance);
    partial void DeletetblEmpleado(tblEmpleado instance);
    partial void InserttblEstado(tblEstado instance);
    partial void UpdatetblEstado(tblEstado instance);
    partial void DeletetblEstado(tblEstado instance);
    partial void InserttblEstado_Municipio(tblEstado_Municipio instance);
    partial void UpdatetblEstado_Municipio(tblEstado_Municipio instance);
    partial void DeletetblEstado_Municipio(tblEstado_Municipio instance);
    partial void InsertTblMunicipio(TblMunicipio instance);
    partial void UpdateTblMunicipio(TblMunicipio instance);
    partial void DeleteTblMunicipio(TblMunicipio instance);
    partial void InserttblTelefono(tblTelefono instance);
    partial void UpdatetblTelefono(tblTelefono instance);
    partial void DeletetblTelefono(tblTelefono instance);
    partial void InserttblTotalVenta(tblTotalVenta instance);
    partial void UpdatetblTotalVenta(tblTotalVenta instance);
    partial void DeletetblTotalVenta(tblTotalVenta instance);
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    partial void InserttblVenta(tblVenta instance);
    partial void UpdatetblVenta(tblVenta instance);
    partial void DeletetblVenta(tblVenta instance);
    #endregion
		
		public PaslumBaseDatoDataContext() : 
				base(global::Modelo.Properties.Settings.Default.XIUGARConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PaslumBaseDatoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaslumBaseDatoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaslumBaseDatoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaslumBaseDatoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAlmacen> tblAlmacen
		{
			get
			{
				return this.GetTable<tblAlmacen>();
			}
		}
		
		public System.Data.Linq.Table<tblCliente> tblCliente
		{
			get
			{
				return this.GetTable<tblCliente>();
			}
		}
		
		public System.Data.Linq.Table<tblDireccion> tblDireccion
		{
			get
			{
				return this.GetTable<tblDireccion>();
			}
		}
		
		public System.Data.Linq.Table<tblEmpleado> tblEmpleado
		{
			get
			{
				return this.GetTable<tblEmpleado>();
			}
		}
		
		public System.Data.Linq.Table<tblEstado> tblEstado
		{
			get
			{
				return this.GetTable<tblEstado>();
			}
		}
		
		public System.Data.Linq.Table<tblEstado_Municipio> tblEstado_Municipio
		{
			get
			{
				return this.GetTable<tblEstado_Municipio>();
			}
		}
		
		public System.Data.Linq.Table<TblMunicipio> TblMunicipio
		{
			get
			{
				return this.GetTable<TblMunicipio>();
			}
		}
		
		public System.Data.Linq.Table<tblTelefono> tblTelefono
		{
			get
			{
				return this.GetTable<tblTelefono>();
			}
		}
		
		public System.Data.Linq.Table<tblTotalVenta> tblTotalVenta
		{
			get
			{
				return this.GetTable<tblTotalVenta>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuario
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tblVenta> tblVenta
		{
			get
			{
				return this.GetTable<tblVenta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAlmacen")]
	public partial class tblAlmacen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAlmacen;
		
		private string _strNombre;
		
		private string _strDescripcion;
		
		private System.Nullable<int> _intCapacidad;
		
		private System.Nullable<int> _fkEncargado;
		
		private EntityRef<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAlmacenChanging(int value);
    partial void OnidAlmacenChanged();
    partial void OnstrNombreChanging(string value);
    partial void OnstrNombreChanged();
    partial void OnstrDescripcionChanging(string value);
    partial void OnstrDescripcionChanged();
    partial void OnintCapacidadChanging(System.Nullable<int> value);
    partial void OnintCapacidadChanged();
    partial void OnfkEncargadoChanging(System.Nullable<int> value);
    partial void OnfkEncargadoChanged();
    #endregion
		
		public tblAlmacen()
		{
			this._tblEmpleado = default(EntityRef<tblEmpleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAlmacen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAlmacen
		{
			get
			{
				return this._idAlmacen;
			}
			set
			{
				if ((this._idAlmacen != value))
				{
					this.OnidAlmacenChanging(value);
					this.SendPropertyChanging();
					this._idAlmacen = value;
					this.SendPropertyChanged("idAlmacen");
					this.OnidAlmacenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string strNombre
		{
			get
			{
				return this._strNombre;
			}
			set
			{
				if ((this._strNombre != value))
				{
					this.OnstrNombreChanging(value);
					this.SendPropertyChanging();
					this._strNombre = value;
					this.SendPropertyChanged("strNombre");
					this.OnstrNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDescripcion", DbType="VarChar(250)")]
		public string strDescripcion
		{
			get
			{
				return this._strDescripcion;
			}
			set
			{
				if ((this._strDescripcion != value))
				{
					this.OnstrDescripcionChanging(value);
					this.SendPropertyChanging();
					this._strDescripcion = value;
					this.SendPropertyChanged("strDescripcion");
					this.OnstrDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCapacidad", DbType="Int")]
		public System.Nullable<int> intCapacidad
		{
			get
			{
				return this._intCapacidad;
			}
			set
			{
				if ((this._intCapacidad != value))
				{
					this.OnintCapacidadChanging(value);
					this.SendPropertyChanging();
					this._intCapacidad = value;
					this.SendPropertyChanged("intCapacidad");
					this.OnintCapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkEncargado", DbType="Int")]
		public System.Nullable<int> fkEncargado
		{
			get
			{
				return this._fkEncargado;
			}
			set
			{
				if ((this._fkEncargado != value))
				{
					if (this._tblEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkEncargadoChanging(value);
					this.SendPropertyChanging();
					this._fkEncargado = value;
					this.SendPropertyChanged("fkEncargado");
					this.OnfkEncargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblAlmacen", Storage="_tblEmpleado", ThisKey="fkEncargado", OtherKey="idEmpleado", IsForeignKey=true)]
		public tblEmpleado tblEmpleado
		{
			get
			{
				return this._tblEmpleado.Entity;
			}
			set
			{
				tblEmpleado previousValue = this._tblEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._tblEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmpleado.Entity = null;
						previousValue.tblAlmacen.Remove(this);
					}
					this._tblEmpleado.Entity = value;
					if ((value != null))
					{
						value.tblAlmacen.Add(this);
						this._fkEncargado = value.idEmpleado;
					}
					else
					{
						this._fkEncargado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEmpleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCliente")]
	public partial class tblCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCliente;
		
		private string _strNombre;
		
		private string _strApellidoP;
		
		private string _strApellidoM;
		
		private string _strSituacionFiscal;
		
		private string _strCorreo;
		
		private string _strEntrega;
		
		private string _strHorario;
		
		private string _strMetodoPago;
		
		private System.Nullable<int> _fkDireccion;
		
		private System.Nullable<int> _fkTelefono;
		
		private System.Nullable<int> _fkLogin;
		
		private EntityRef<tblDireccion> _tblDireccion;
		
		private EntityRef<tblTelefono> _tblTelefono;
		
		private EntityRef<tblUsuario> _tblUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnstrNombreChanging(string value);
    partial void OnstrNombreChanged();
    partial void OnstrApellidoPChanging(string value);
    partial void OnstrApellidoPChanged();
    partial void OnstrApellidoMChanging(string value);
    partial void OnstrApellidoMChanged();
    partial void OnstrSituacionFiscalChanging(string value);
    partial void OnstrSituacionFiscalChanged();
    partial void OnstrCorreoChanging(string value);
    partial void OnstrCorreoChanged();
    partial void OnstrEntregaChanging(string value);
    partial void OnstrEntregaChanged();
    partial void OnstrHorarioChanging(string value);
    partial void OnstrHorarioChanged();
    partial void OnstrMetodoPagoChanging(string value);
    partial void OnstrMetodoPagoChanged();
    partial void OnfkDireccionChanging(System.Nullable<int> value);
    partial void OnfkDireccionChanged();
    partial void OnfkTelefonoChanging(System.Nullable<int> value);
    partial void OnfkTelefonoChanged();
    partial void OnfkLoginChanging(System.Nullable<int> value);
    partial void OnfkLoginChanged();
    #endregion
		
		public tblCliente()
		{
			this._tblDireccion = default(EntityRef<tblDireccion>);
			this._tblTelefono = default(EntityRef<tblTelefono>);
			this._tblUsuario = default(EntityRef<tblUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strNombre
		{
			get
			{
				return this._strNombre;
			}
			set
			{
				if ((this._strNombre != value))
				{
					this.OnstrNombreChanging(value);
					this.SendPropertyChanging();
					this._strNombre = value;
					this.SendPropertyChanged("strNombre");
					this.OnstrNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strApellidoP", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strApellidoP
		{
			get
			{
				return this._strApellidoP;
			}
			set
			{
				if ((this._strApellidoP != value))
				{
					this.OnstrApellidoPChanging(value);
					this.SendPropertyChanging();
					this._strApellidoP = value;
					this.SendPropertyChanged("strApellidoP");
					this.OnstrApellidoPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strApellidoM", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strApellidoM
		{
			get
			{
				return this._strApellidoM;
			}
			set
			{
				if ((this._strApellidoM != value))
				{
					this.OnstrApellidoMChanging(value);
					this.SendPropertyChanging();
					this._strApellidoM = value;
					this.SendPropertyChanged("strApellidoM");
					this.OnstrApellidoMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strSituacionFiscal", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strSituacionFiscal
		{
			get
			{
				return this._strSituacionFiscal;
			}
			set
			{
				if ((this._strSituacionFiscal != value))
				{
					this.OnstrSituacionFiscalChanging(value);
					this.SendPropertyChanging();
					this._strSituacionFiscal = value;
					this.SendPropertyChanged("strSituacionFiscal");
					this.OnstrSituacionFiscalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCorreo", DbType="VarChar(150)")]
		public string strCorreo
		{
			get
			{
				return this._strCorreo;
			}
			set
			{
				if ((this._strCorreo != value))
				{
					this.OnstrCorreoChanging(value);
					this.SendPropertyChanging();
					this._strCorreo = value;
					this.SendPropertyChanged("strCorreo");
					this.OnstrCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strEntrega", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strEntrega
		{
			get
			{
				return this._strEntrega;
			}
			set
			{
				if ((this._strEntrega != value))
				{
					this.OnstrEntregaChanging(value);
					this.SendPropertyChanging();
					this._strEntrega = value;
					this.SendPropertyChanged("strEntrega");
					this.OnstrEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strHorario", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strHorario
		{
			get
			{
				return this._strHorario;
			}
			set
			{
				if ((this._strHorario != value))
				{
					this.OnstrHorarioChanging(value);
					this.SendPropertyChanging();
					this._strHorario = value;
					this.SendPropertyChanged("strHorario");
					this.OnstrHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strMetodoPago", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strMetodoPago
		{
			get
			{
				return this._strMetodoPago;
			}
			set
			{
				if ((this._strMetodoPago != value))
				{
					this.OnstrMetodoPagoChanging(value);
					this.SendPropertyChanging();
					this._strMetodoPago = value;
					this.SendPropertyChanged("strMetodoPago");
					this.OnstrMetodoPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkDireccion", DbType="Int")]
		public System.Nullable<int> fkDireccion
		{
			get
			{
				return this._fkDireccion;
			}
			set
			{
				if ((this._fkDireccion != value))
				{
					if (this._tblDireccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkDireccionChanging(value);
					this.SendPropertyChanging();
					this._fkDireccion = value;
					this.SendPropertyChanged("fkDireccion");
					this.OnfkDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkTelefono", DbType="Int")]
		public System.Nullable<int> fkTelefono
		{
			get
			{
				return this._fkTelefono;
			}
			set
			{
				if ((this._fkTelefono != value))
				{
					if (this._tblTelefono.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkTelefonoChanging(value);
					this.SendPropertyChanging();
					this._fkTelefono = value;
					this.SendPropertyChanged("fkTelefono");
					this.OnfkTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkLogin", DbType="Int")]
		public System.Nullable<int> fkLogin
		{
			get
			{
				return this._fkLogin;
			}
			set
			{
				if ((this._fkLogin != value))
				{
					if (this._tblUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkLoginChanging(value);
					this.SendPropertyChanging();
					this._fkLogin = value;
					this.SendPropertyChanged("fkLogin");
					this.OnfkLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDireccion_tblCliente", Storage="_tblDireccion", ThisKey="fkDireccion", OtherKey="idDireccion", IsForeignKey=true)]
		public tblDireccion tblDireccion
		{
			get
			{
				return this._tblDireccion.Entity;
			}
			set
			{
				tblDireccion previousValue = this._tblDireccion.Entity;
				if (((previousValue != value) 
							|| (this._tblDireccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDireccion.Entity = null;
						previousValue.tblCliente.Remove(this);
					}
					this._tblDireccion.Entity = value;
					if ((value != null))
					{
						value.tblCliente.Add(this);
						this._fkDireccion = value.idDireccion;
					}
					else
					{
						this._fkDireccion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDireccion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTelefono_tblCliente", Storage="_tblTelefono", ThisKey="fkTelefono", OtherKey="idTelefono", IsForeignKey=true)]
		public tblTelefono tblTelefono
		{
			get
			{
				return this._tblTelefono.Entity;
			}
			set
			{
				tblTelefono previousValue = this._tblTelefono.Entity;
				if (((previousValue != value) 
							|| (this._tblTelefono.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTelefono.Entity = null;
						previousValue.tblCliente.Remove(this);
					}
					this._tblTelefono.Entity = value;
					if ((value != null))
					{
						value.tblCliente.Add(this);
						this._fkTelefono = value.idTelefono;
					}
					else
					{
						this._fkTelefono = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblTelefono");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblCliente", Storage="_tblUsuario", ThisKey="fkLogin", OtherKey="idUsuario", IsForeignKey=true)]
		public tblUsuario tblUsuario
		{
			get
			{
				return this._tblUsuario.Entity;
			}
			set
			{
				tblUsuario previousValue = this._tblUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tblUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUsuario.Entity = null;
						previousValue.tblCliente.Remove(this);
					}
					this._tblUsuario.Entity = value;
					if ((value != null))
					{
						value.tblCliente.Add(this);
						this._fkLogin = value.idUsuario;
					}
					else
					{
						this._fkLogin = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDireccion")]
	public partial class tblDireccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDireccion;
		
		private string _strColonia;
		
		private string _strCalle;
		
		private string _intCodpost;
		
		private string _strNumInt;
		
		private string _strNumExt;
		
		private string _strReferencias;
		
		private System.Nullable<int> _fkEstadoMunicipio;
		
		private EntitySet<tblCliente> _tblCliente;
		
		private EntitySet<tblEmpleado> _tblEmpleado;
		
		private EntityRef<tblEstado_Municipio> _tblEstado_Municipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDireccionChanging(int value);
    partial void OnidDireccionChanged();
    partial void OnstrColoniaChanging(string value);
    partial void OnstrColoniaChanged();
    partial void OnstrCalleChanging(string value);
    partial void OnstrCalleChanged();
    partial void OnintCodpostChanging(string value);
    partial void OnintCodpostChanged();
    partial void OnstrNumIntChanging(string value);
    partial void OnstrNumIntChanged();
    partial void OnstrNumExtChanging(string value);
    partial void OnstrNumExtChanged();
    partial void OnstrReferenciasChanging(string value);
    partial void OnstrReferenciasChanged();
    partial void OnfkEstadoMunicipioChanging(System.Nullable<int> value);
    partial void OnfkEstadoMunicipioChanged();
    #endregion
		
		public tblDireccion()
		{
			this._tblCliente = new EntitySet<tblCliente>(new Action<tblCliente>(this.attach_tblCliente), new Action<tblCliente>(this.detach_tblCliente));
			this._tblEmpleado = new EntitySet<tblEmpleado>(new Action<tblEmpleado>(this.attach_tblEmpleado), new Action<tblEmpleado>(this.detach_tblEmpleado));
			this._tblEstado_Municipio = default(EntityRef<tblEstado_Municipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDireccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDireccion
		{
			get
			{
				return this._idDireccion;
			}
			set
			{
				if ((this._idDireccion != value))
				{
					this.OnidDireccionChanging(value);
					this.SendPropertyChanging();
					this._idDireccion = value;
					this.SendPropertyChanged("idDireccion");
					this.OnidDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strColonia", DbType="VarChar(150)")]
		public string strColonia
		{
			get
			{
				return this._strColonia;
			}
			set
			{
				if ((this._strColonia != value))
				{
					this.OnstrColoniaChanging(value);
					this.SendPropertyChanging();
					this._strColonia = value;
					this.SendPropertyChanged("strColonia");
					this.OnstrColoniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCalle", DbType="VarChar(150)")]
		public string strCalle
		{
			get
			{
				return this._strCalle;
			}
			set
			{
				if ((this._strCalle != value))
				{
					this.OnstrCalleChanging(value);
					this.SendPropertyChanging();
					this._strCalle = value;
					this.SendPropertyChanged("strCalle");
					this.OnstrCalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCodpost", DbType="VarChar(10)")]
		public string intCodpost
		{
			get
			{
				return this._intCodpost;
			}
			set
			{
				if ((this._intCodpost != value))
				{
					this.OnintCodpostChanging(value);
					this.SendPropertyChanging();
					this._intCodpost = value;
					this.SendPropertyChanged("intCodpost");
					this.OnintCodpostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNumInt", DbType="VarChar(50)")]
		public string strNumInt
		{
			get
			{
				return this._strNumInt;
			}
			set
			{
				if ((this._strNumInt != value))
				{
					this.OnstrNumIntChanging(value);
					this.SendPropertyChanging();
					this._strNumInt = value;
					this.SendPropertyChanged("strNumInt");
					this.OnstrNumIntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNumExt", DbType="VarChar(50)")]
		public string strNumExt
		{
			get
			{
				return this._strNumExt;
			}
			set
			{
				if ((this._strNumExt != value))
				{
					this.OnstrNumExtChanging(value);
					this.SendPropertyChanging();
					this._strNumExt = value;
					this.SendPropertyChanged("strNumExt");
					this.OnstrNumExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strReferencias", DbType="VarChar(400)")]
		public string strReferencias
		{
			get
			{
				return this._strReferencias;
			}
			set
			{
				if ((this._strReferencias != value))
				{
					this.OnstrReferenciasChanging(value);
					this.SendPropertyChanging();
					this._strReferencias = value;
					this.SendPropertyChanged("strReferencias");
					this.OnstrReferenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkEstadoMunicipio", DbType="Int")]
		public System.Nullable<int> fkEstadoMunicipio
		{
			get
			{
				return this._fkEstadoMunicipio;
			}
			set
			{
				if ((this._fkEstadoMunicipio != value))
				{
					if (this._tblEstado_Municipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkEstadoMunicipioChanging(value);
					this.SendPropertyChanging();
					this._fkEstadoMunicipio = value;
					this.SendPropertyChanged("fkEstadoMunicipio");
					this.OnfkEstadoMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDireccion_tblCliente", Storage="_tblCliente", ThisKey="idDireccion", OtherKey="fkDireccion")]
		public EntitySet<tblCliente> tblCliente
		{
			get
			{
				return this._tblCliente;
			}
			set
			{
				this._tblCliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDireccion_tblEmpleado", Storage="_tblEmpleado", ThisKey="idDireccion", OtherKey="fkDireccion")]
		public EntitySet<tblEmpleado> tblEmpleado
		{
			get
			{
				return this._tblEmpleado;
			}
			set
			{
				this._tblEmpleado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEstado_Municipio_tblDireccion", Storage="_tblEstado_Municipio", ThisKey="fkEstadoMunicipio", OtherKey="idEstado_Municipio", IsForeignKey=true)]
		public tblEstado_Municipio tblEstado_Municipio
		{
			get
			{
				return this._tblEstado_Municipio.Entity;
			}
			set
			{
				tblEstado_Municipio previousValue = this._tblEstado_Municipio.Entity;
				if (((previousValue != value) 
							|| (this._tblEstado_Municipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEstado_Municipio.Entity = null;
						previousValue.tblDireccion.Remove(this);
					}
					this._tblEstado_Municipio.Entity = value;
					if ((value != null))
					{
						value.tblDireccion.Add(this);
						this._fkEstadoMunicipio = value.idEstado_Municipio;
					}
					else
					{
						this._fkEstadoMunicipio = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEstado_Municipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCliente(tblCliente entity)
		{
			this.SendPropertyChanging();
			entity.tblDireccion = this;
		}
		
		private void detach_tblCliente(tblCliente entity)
		{
			this.SendPropertyChanging();
			entity.tblDireccion = null;
		}
		
		private void attach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblDireccion = this;
		}
		
		private void detach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblDireccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmpleado")]
	public partial class tblEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private string _strNombre;
		
		private string _strApellidoP;
		
		private string _strApellidoM;
		
		private string _strCorreo;
		
		private string _strSexo;
		
		private string _strEdad;
		
		private System.Nullable<int> _fkDireccion;
		
		private System.Nullable<int> _fkTelefono;
		
		private System.Nullable<int> _fkLogin;
		
		private EntitySet<tblAlmacen> _tblAlmacen;
		
		private EntitySet<tblVenta> _tblVenta;
		
		private EntityRef<tblDireccion> _tblDireccion;
		
		private EntityRef<tblTelefono> _tblTelefono;
		
		private EntityRef<tblUsuario> _tblUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnstrNombreChanging(string value);
    partial void OnstrNombreChanged();
    partial void OnstrApellidoPChanging(string value);
    partial void OnstrApellidoPChanged();
    partial void OnstrApellidoMChanging(string value);
    partial void OnstrApellidoMChanged();
    partial void OnstrCorreoChanging(string value);
    partial void OnstrCorreoChanged();
    partial void OnstrSexoChanging(string value);
    partial void OnstrSexoChanged();
    partial void OnstrEdadChanging(string value);
    partial void OnstrEdadChanged();
    partial void OnfkDireccionChanging(System.Nullable<int> value);
    partial void OnfkDireccionChanged();
    partial void OnfkTelefonoChanging(System.Nullable<int> value);
    partial void OnfkTelefonoChanged();
    partial void OnfkLoginChanging(System.Nullable<int> value);
    partial void OnfkLoginChanged();
    #endregion
		
		public tblEmpleado()
		{
			this._tblAlmacen = new EntitySet<tblAlmacen>(new Action<tblAlmacen>(this.attach_tblAlmacen), new Action<tblAlmacen>(this.detach_tblAlmacen));
			this._tblVenta = new EntitySet<tblVenta>(new Action<tblVenta>(this.attach_tblVenta), new Action<tblVenta>(this.detach_tblVenta));
			this._tblDireccion = default(EntityRef<tblDireccion>);
			this._tblTelefono = default(EntityRef<tblTelefono>);
			this._tblUsuario = default(EntityRef<tblUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strNombre
		{
			get
			{
				return this._strNombre;
			}
			set
			{
				if ((this._strNombre != value))
				{
					this.OnstrNombreChanging(value);
					this.SendPropertyChanging();
					this._strNombre = value;
					this.SendPropertyChanged("strNombre");
					this.OnstrNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strApellidoP", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strApellidoP
		{
			get
			{
				return this._strApellidoP;
			}
			set
			{
				if ((this._strApellidoP != value))
				{
					this.OnstrApellidoPChanging(value);
					this.SendPropertyChanging();
					this._strApellidoP = value;
					this.SendPropertyChanged("strApellidoP");
					this.OnstrApellidoPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strApellidoM", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string strApellidoM
		{
			get
			{
				return this._strApellidoM;
			}
			set
			{
				if ((this._strApellidoM != value))
				{
					this.OnstrApellidoMChanging(value);
					this.SendPropertyChanging();
					this._strApellidoM = value;
					this.SendPropertyChanged("strApellidoM");
					this.OnstrApellidoMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCorreo", DbType="VarChar(150)")]
		public string strCorreo
		{
			get
			{
				return this._strCorreo;
			}
			set
			{
				if ((this._strCorreo != value))
				{
					this.OnstrCorreoChanging(value);
					this.SendPropertyChanging();
					this._strCorreo = value;
					this.SendPropertyChanged("strCorreo");
					this.OnstrCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strSexo", DbType="VarChar(50)")]
		public string strSexo
		{
			get
			{
				return this._strSexo;
			}
			set
			{
				if ((this._strSexo != value))
				{
					this.OnstrSexoChanging(value);
					this.SendPropertyChanging();
					this._strSexo = value;
					this.SendPropertyChanged("strSexo");
					this.OnstrSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strEdad", DbType="VarChar(50)")]
		public string strEdad
		{
			get
			{
				return this._strEdad;
			}
			set
			{
				if ((this._strEdad != value))
				{
					this.OnstrEdadChanging(value);
					this.SendPropertyChanging();
					this._strEdad = value;
					this.SendPropertyChanged("strEdad");
					this.OnstrEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkDireccion", DbType="Int")]
		public System.Nullable<int> fkDireccion
		{
			get
			{
				return this._fkDireccion;
			}
			set
			{
				if ((this._fkDireccion != value))
				{
					if (this._tblDireccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkDireccionChanging(value);
					this.SendPropertyChanging();
					this._fkDireccion = value;
					this.SendPropertyChanged("fkDireccion");
					this.OnfkDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkTelefono", DbType="Int")]
		public System.Nullable<int> fkTelefono
		{
			get
			{
				return this._fkTelefono;
			}
			set
			{
				if ((this._fkTelefono != value))
				{
					if (this._tblTelefono.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkTelefonoChanging(value);
					this.SendPropertyChanging();
					this._fkTelefono = value;
					this.SendPropertyChanged("fkTelefono");
					this.OnfkTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkLogin", DbType="Int")]
		public System.Nullable<int> fkLogin
		{
			get
			{
				return this._fkLogin;
			}
			set
			{
				if ((this._fkLogin != value))
				{
					if (this._tblUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkLoginChanging(value);
					this.SendPropertyChanging();
					this._fkLogin = value;
					this.SendPropertyChanged("fkLogin");
					this.OnfkLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblAlmacen", Storage="_tblAlmacen", ThisKey="idEmpleado", OtherKey="fkEncargado")]
		public EntitySet<tblAlmacen> tblAlmacen
		{
			get
			{
				return this._tblAlmacen;
			}
			set
			{
				this._tblAlmacen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblVenta", Storage="_tblVenta", ThisKey="idEmpleado", OtherKey="fkEmpleado")]
		public EntitySet<tblVenta> tblVenta
		{
			get
			{
				return this._tblVenta;
			}
			set
			{
				this._tblVenta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDireccion_tblEmpleado", Storage="_tblDireccion", ThisKey="fkDireccion", OtherKey="idDireccion", IsForeignKey=true)]
		public tblDireccion tblDireccion
		{
			get
			{
				return this._tblDireccion.Entity;
			}
			set
			{
				tblDireccion previousValue = this._tblDireccion.Entity;
				if (((previousValue != value) 
							|| (this._tblDireccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDireccion.Entity = null;
						previousValue.tblEmpleado.Remove(this);
					}
					this._tblDireccion.Entity = value;
					if ((value != null))
					{
						value.tblEmpleado.Add(this);
						this._fkDireccion = value.idDireccion;
					}
					else
					{
						this._fkDireccion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDireccion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTelefono_tblEmpleado", Storage="_tblTelefono", ThisKey="fkTelefono", OtherKey="idTelefono", IsForeignKey=true)]
		public tblTelefono tblTelefono
		{
			get
			{
				return this._tblTelefono.Entity;
			}
			set
			{
				tblTelefono previousValue = this._tblTelefono.Entity;
				if (((previousValue != value) 
							|| (this._tblTelefono.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTelefono.Entity = null;
						previousValue.tblEmpleado.Remove(this);
					}
					this._tblTelefono.Entity = value;
					if ((value != null))
					{
						value.tblEmpleado.Add(this);
						this._fkTelefono = value.idTelefono;
					}
					else
					{
						this._fkTelefono = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblTelefono");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblEmpleado", Storage="_tblUsuario", ThisKey="fkLogin", OtherKey="idUsuario", IsForeignKey=true)]
		public tblUsuario tblUsuario
		{
			get
			{
				return this._tblUsuario.Entity;
			}
			set
			{
				tblUsuario previousValue = this._tblUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tblUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUsuario.Entity = null;
						previousValue.tblEmpleado.Remove(this);
					}
					this._tblUsuario.Entity = value;
					if ((value != null))
					{
						value.tblEmpleado.Add(this);
						this._fkLogin = value.idUsuario;
					}
					else
					{
						this._fkLogin = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblAlmacen(tblAlmacen entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = this;
		}
		
		private void detach_tblAlmacen(tblAlmacen entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = null;
		}
		
		private void attach_tblVenta(tblVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = this;
		}
		
		private void detach_tblVenta(tblVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEstado")]
	public partial class tblEstado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEstado;
		
		private string _strEstado;
		
		private EntitySet<tblEstado_Municipio> _tblEstado_Municipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEstadoChanging(int value);
    partial void OnidEstadoChanged();
    partial void OnstrEstadoChanging(string value);
    partial void OnstrEstadoChanged();
    #endregion
		
		public tblEstado()
		{
			this._tblEstado_Municipio = new EntitySet<tblEstado_Municipio>(new Action<tblEstado_Municipio>(this.attach_tblEstado_Municipio), new Action<tblEstado_Municipio>(this.detach_tblEstado_Municipio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEstado
		{
			get
			{
				return this._idEstado;
			}
			set
			{
				if ((this._idEstado != value))
				{
					this.OnidEstadoChanging(value);
					this.SendPropertyChanging();
					this._idEstado = value;
					this.SendPropertyChanged("idEstado");
					this.OnidEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strEstado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string strEstado
		{
			get
			{
				return this._strEstado;
			}
			set
			{
				if ((this._strEstado != value))
				{
					this.OnstrEstadoChanging(value);
					this.SendPropertyChanging();
					this._strEstado = value;
					this.SendPropertyChanged("strEstado");
					this.OnstrEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEstado_tblEstado_Municipio", Storage="_tblEstado_Municipio", ThisKey="idEstado", OtherKey="fkEstado")]
		public EntitySet<tblEstado_Municipio> tblEstado_Municipio
		{
			get
			{
				return this._tblEstado_Municipio;
			}
			set
			{
				this._tblEstado_Municipio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblEstado_Municipio(tblEstado_Municipio entity)
		{
			this.SendPropertyChanging();
			entity.tblEstado = this;
		}
		
		private void detach_tblEstado_Municipio(tblEstado_Municipio entity)
		{
			this.SendPropertyChanging();
			entity.tblEstado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEstado_Municipio")]
	public partial class tblEstado_Municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEstado_Municipio;
		
		private int _fkEstado;
		
		private int _fkMunicipio;
		
		private EntitySet<tblDireccion> _tblDireccion;
		
		private EntityRef<tblEstado> _tblEstado;
		
		private EntityRef<TblMunicipio> _TblMunicipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEstado_MunicipioChanging(int value);
    partial void OnidEstado_MunicipioChanged();
    partial void OnfkEstadoChanging(int value);
    partial void OnfkEstadoChanged();
    partial void OnfkMunicipioChanging(int value);
    partial void OnfkMunicipioChanged();
    #endregion
		
		public tblEstado_Municipio()
		{
			this._tblDireccion = new EntitySet<tblDireccion>(new Action<tblDireccion>(this.attach_tblDireccion), new Action<tblDireccion>(this.detach_tblDireccion));
			this._tblEstado = default(EntityRef<tblEstado>);
			this._TblMunicipio = default(EntityRef<TblMunicipio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstado_Municipio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEstado_Municipio
		{
			get
			{
				return this._idEstado_Municipio;
			}
			set
			{
				if ((this._idEstado_Municipio != value))
				{
					this.OnidEstado_MunicipioChanging(value);
					this.SendPropertyChanging();
					this._idEstado_Municipio = value;
					this.SendPropertyChanged("idEstado_Municipio");
					this.OnidEstado_MunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkEstado", DbType="Int NOT NULL")]
		public int fkEstado
		{
			get
			{
				return this._fkEstado;
			}
			set
			{
				if ((this._fkEstado != value))
				{
					if (this._tblEstado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkEstadoChanging(value);
					this.SendPropertyChanging();
					this._fkEstado = value;
					this.SendPropertyChanged("fkEstado");
					this.OnfkEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkMunicipio", DbType="Int NOT NULL")]
		public int fkMunicipio
		{
			get
			{
				return this._fkMunicipio;
			}
			set
			{
				if ((this._fkMunicipio != value))
				{
					if (this._TblMunicipio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkMunicipioChanging(value);
					this.SendPropertyChanging();
					this._fkMunicipio = value;
					this.SendPropertyChanged("fkMunicipio");
					this.OnfkMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEstado_Municipio_tblDireccion", Storage="_tblDireccion", ThisKey="idEstado_Municipio", OtherKey="fkEstadoMunicipio")]
		public EntitySet<tblDireccion> tblDireccion
		{
			get
			{
				return this._tblDireccion;
			}
			set
			{
				this._tblDireccion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEstado_tblEstado_Municipio", Storage="_tblEstado", ThisKey="fkEstado", OtherKey="idEstado", IsForeignKey=true)]
		public tblEstado tblEstado
		{
			get
			{
				return this._tblEstado.Entity;
			}
			set
			{
				tblEstado previousValue = this._tblEstado.Entity;
				if (((previousValue != value) 
							|| (this._tblEstado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEstado.Entity = null;
						previousValue.tblEstado_Municipio.Remove(this);
					}
					this._tblEstado.Entity = value;
					if ((value != null))
					{
						value.tblEstado_Municipio.Add(this);
						this._fkEstado = value.idEstado;
					}
					else
					{
						this._fkEstado = default(int);
					}
					this.SendPropertyChanged("tblEstado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblMunicipio_tblEstado_Municipio", Storage="_TblMunicipio", ThisKey="fkMunicipio", OtherKey="idMunicipio", IsForeignKey=true)]
		public TblMunicipio TblMunicipio
		{
			get
			{
				return this._TblMunicipio.Entity;
			}
			set
			{
				TblMunicipio previousValue = this._TblMunicipio.Entity;
				if (((previousValue != value) 
							|| (this._TblMunicipio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblMunicipio.Entity = null;
						previousValue.tblEstado_Municipio.Remove(this);
					}
					this._TblMunicipio.Entity = value;
					if ((value != null))
					{
						value.tblEstado_Municipio.Add(this);
						this._fkMunicipio = value.idMunicipio;
					}
					else
					{
						this._fkMunicipio = default(int);
					}
					this.SendPropertyChanged("TblMunicipio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDireccion(tblDireccion entity)
		{
			this.SendPropertyChanging();
			entity.tblEstado_Municipio = this;
		}
		
		private void detach_tblDireccion(tblDireccion entity)
		{
			this.SendPropertyChanging();
			entity.tblEstado_Municipio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblMunicipio")]
	public partial class TblMunicipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMunicipio;
		
		private string _strMunicipio;
		
		private EntitySet<tblEstado_Municipio> _tblEstado_Municipio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMunicipioChanging(int value);
    partial void OnidMunicipioChanged();
    partial void OnstrMunicipioChanging(string value);
    partial void OnstrMunicipioChanged();
    #endregion
		
		public TblMunicipio()
		{
			this._tblEstado_Municipio = new EntitySet<tblEstado_Municipio>(new Action<tblEstado_Municipio>(this.attach_tblEstado_Municipio), new Action<tblEstado_Municipio>(this.detach_tblEstado_Municipio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMunicipio
		{
			get
			{
				return this._idMunicipio;
			}
			set
			{
				if ((this._idMunicipio != value))
				{
					this.OnidMunicipioChanging(value);
					this.SendPropertyChanging();
					this._idMunicipio = value;
					this.SendPropertyChanged("idMunicipio");
					this.OnidMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strMunicipio", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string strMunicipio
		{
			get
			{
				return this._strMunicipio;
			}
			set
			{
				if ((this._strMunicipio != value))
				{
					this.OnstrMunicipioChanging(value);
					this.SendPropertyChanging();
					this._strMunicipio = value;
					this.SendPropertyChanged("strMunicipio");
					this.OnstrMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblMunicipio_tblEstado_Municipio", Storage="_tblEstado_Municipio", ThisKey="idMunicipio", OtherKey="fkMunicipio")]
		public EntitySet<tblEstado_Municipio> tblEstado_Municipio
		{
			get
			{
				return this._tblEstado_Municipio;
			}
			set
			{
				this._tblEstado_Municipio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblEstado_Municipio(tblEstado_Municipio entity)
		{
			this.SendPropertyChanging();
			entity.TblMunicipio = this;
		}
		
		private void detach_tblEstado_Municipio(tblEstado_Municipio entity)
		{
			this.SendPropertyChanging();
			entity.TblMunicipio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTelefono")]
	public partial class tblTelefono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTelefono;
		
		private string _strCelular;
		
		private string _strTelCasa;
		
		private string _strOtro;
		
		private EntitySet<tblCliente> _tblCliente;
		
		private EntitySet<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTelefonoChanging(int value);
    partial void OnidTelefonoChanged();
    partial void OnstrCelularChanging(string value);
    partial void OnstrCelularChanged();
    partial void OnstrTelCasaChanging(string value);
    partial void OnstrTelCasaChanged();
    partial void OnstrOtroChanging(string value);
    partial void OnstrOtroChanged();
    #endregion
		
		public tblTelefono()
		{
			this._tblCliente = new EntitySet<tblCliente>(new Action<tblCliente>(this.attach_tblCliente), new Action<tblCliente>(this.detach_tblCliente));
			this._tblEmpleado = new EntitySet<tblEmpleado>(new Action<tblEmpleado>(this.attach_tblEmpleado), new Action<tblEmpleado>(this.detach_tblEmpleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTelefono", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTelefono
		{
			get
			{
				return this._idTelefono;
			}
			set
			{
				if ((this._idTelefono != value))
				{
					this.OnidTelefonoChanging(value);
					this.SendPropertyChanging();
					this._idTelefono = value;
					this.SendPropertyChanged("idTelefono");
					this.OnidTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCelular", DbType="VarChar(50)")]
		public string strCelular
		{
			get
			{
				return this._strCelular;
			}
			set
			{
				if ((this._strCelular != value))
				{
					this.OnstrCelularChanging(value);
					this.SendPropertyChanging();
					this._strCelular = value;
					this.SendPropertyChanged("strCelular");
					this.OnstrCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTelCasa", DbType="VarChar(50)")]
		public string strTelCasa
		{
			get
			{
				return this._strTelCasa;
			}
			set
			{
				if ((this._strTelCasa != value))
				{
					this.OnstrTelCasaChanging(value);
					this.SendPropertyChanging();
					this._strTelCasa = value;
					this.SendPropertyChanged("strTelCasa");
					this.OnstrTelCasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strOtro", DbType="VarChar(50)")]
		public string strOtro
		{
			get
			{
				return this._strOtro;
			}
			set
			{
				if ((this._strOtro != value))
				{
					this.OnstrOtroChanging(value);
					this.SendPropertyChanging();
					this._strOtro = value;
					this.SendPropertyChanged("strOtro");
					this.OnstrOtroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTelefono_tblCliente", Storage="_tblCliente", ThisKey="idTelefono", OtherKey="fkTelefono")]
		public EntitySet<tblCliente> tblCliente
		{
			get
			{
				return this._tblCliente;
			}
			set
			{
				this._tblCliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTelefono_tblEmpleado", Storage="_tblEmpleado", ThisKey="idTelefono", OtherKey="fkTelefono")]
		public EntitySet<tblEmpleado> tblEmpleado
		{
			get
			{
				return this._tblEmpleado;
			}
			set
			{
				this._tblEmpleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCliente(tblCliente entity)
		{
			this.SendPropertyChanging();
			entity.tblTelefono = this;
		}
		
		private void detach_tblCliente(tblCliente entity)
		{
			this.SendPropertyChanging();
			entity.tblTelefono = null;
		}
		
		private void attach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblTelefono = this;
		}
		
		private void detach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblTelefono = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTotalVenta")]
	public partial class tblTotalVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTotalVenta;
		
		private System.Nullable<decimal> _dblTotal;
		
		private System.Nullable<int> _fkVenta;
		
		private EntityRef<tblVenta> _tblVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTotalVentaChanging(int value);
    partial void OnidTotalVentaChanged();
    partial void OndblTotalChanging(System.Nullable<decimal> value);
    partial void OndblTotalChanged();
    partial void OnfkVentaChanging(System.Nullable<int> value);
    partial void OnfkVentaChanged();
    #endregion
		
		public tblTotalVenta()
		{
			this._tblVenta = default(EntityRef<tblVenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTotalVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTotalVenta
		{
			get
			{
				return this._idTotalVenta;
			}
			set
			{
				if ((this._idTotalVenta != value))
				{
					this.OnidTotalVentaChanging(value);
					this.SendPropertyChanging();
					this._idTotalVenta = value;
					this.SendPropertyChanged("idTotalVenta");
					this.OnidTotalVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dblTotal", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> dblTotal
		{
			get
			{
				return this._dblTotal;
			}
			set
			{
				if ((this._dblTotal != value))
				{
					this.OndblTotalChanging(value);
					this.SendPropertyChanging();
					this._dblTotal = value;
					this.SendPropertyChanged("dblTotal");
					this.OndblTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkVenta", DbType="Int")]
		public System.Nullable<int> fkVenta
		{
			get
			{
				return this._fkVenta;
			}
			set
			{
				if ((this._fkVenta != value))
				{
					if (this._tblVenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkVentaChanging(value);
					this.SendPropertyChanging();
					this._fkVenta = value;
					this.SendPropertyChanged("fkVenta");
					this.OnfkVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVenta_tblTotalVenta", Storage="_tblVenta", ThisKey="fkVenta", OtherKey="idVenta", IsForeignKey=true)]
		public tblVenta tblVenta
		{
			get
			{
				return this._tblVenta.Entity;
			}
			set
			{
				tblVenta previousValue = this._tblVenta.Entity;
				if (((previousValue != value) 
							|| (this._tblVenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblVenta.Entity = null;
						previousValue.tblTotalVenta.Remove(this);
					}
					this._tblVenta.Entity = value;
					if ((value != null))
					{
						value.tblTotalVenta.Add(this);
						this._fkVenta = value.idVenta;
					}
					else
					{
						this._fkVenta = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblVenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuario")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _strUsuario;
		
		private string _strPassword;
		
		private string _strTipousuario;
		
		private EntitySet<tblCliente> _tblCliente;
		
		private EntitySet<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnstrUsuarioChanging(string value);
    partial void OnstrUsuarioChanged();
    partial void OnstrPasswordChanging(string value);
    partial void OnstrPasswordChanged();
    partial void OnstrTipousuarioChanging(string value);
    partial void OnstrTipousuarioChanged();
    #endregion
		
		public tblUsuario()
		{
			this._tblCliente = new EntitySet<tblCliente>(new Action<tblCliente>(this.attach_tblCliente), new Action<tblCliente>(this.detach_tblCliente));
			this._tblEmpleado = new EntitySet<tblEmpleado>(new Action<tblEmpleado>(this.attach_tblEmpleado), new Action<tblEmpleado>(this.detach_tblEmpleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strUsuario
		{
			get
			{
				return this._strUsuario;
			}
			set
			{
				if ((this._strUsuario != value))
				{
					this.OnstrUsuarioChanging(value);
					this.SendPropertyChanging();
					this._strUsuario = value;
					this.SendPropertyChanged("strUsuario");
					this.OnstrUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strPassword
		{
			get
			{
				return this._strPassword;
			}
			set
			{
				if ((this._strPassword != value))
				{
					this.OnstrPasswordChanging(value);
					this.SendPropertyChanging();
					this._strPassword = value;
					this.SendPropertyChanged("strPassword");
					this.OnstrPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTipousuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strTipousuario
		{
			get
			{
				return this._strTipousuario;
			}
			set
			{
				if ((this._strTipousuario != value))
				{
					this.OnstrTipousuarioChanging(value);
					this.SendPropertyChanging();
					this._strTipousuario = value;
					this.SendPropertyChanged("strTipousuario");
					this.OnstrTipousuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblCliente", Storage="_tblCliente", ThisKey="idUsuario", OtherKey="fkLogin")]
		public EntitySet<tblCliente> tblCliente
		{
			get
			{
				return this._tblCliente;
			}
			set
			{
				this._tblCliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUsuario_tblEmpleado", Storage="_tblEmpleado", ThisKey="idUsuario", OtherKey="fkLogin")]
		public EntitySet<tblEmpleado> tblEmpleado
		{
			get
			{
				return this._tblEmpleado;
			}
			set
			{
				this._tblEmpleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCliente(tblCliente entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = this;
		}
		
		private void detach_tblCliente(tblCliente entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = null;
		}
		
		private void attach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = this;
		}
		
		private void detach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVenta")]
	public partial class tblVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVenta;
		
		private System.Data.Linq.Binary _Fecha;
		
		private int _intBulto;
		
		private int _intKilos;
		
		private string _strDescripcion;
		
		private int _intImporte;
		
		private string _strMetodoPago;
		
		private string _strlapso;
		
		private System.Nullable<int> _fkEmpleado;
		
		private EntitySet<tblTotalVenta> _tblTotalVenta;
		
		private EntityRef<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVentaChanging(int value);
    partial void OnidVentaChanged();
    partial void OnFechaChanging(System.Data.Linq.Binary value);
    partial void OnFechaChanged();
    partial void OnintBultoChanging(int value);
    partial void OnintBultoChanged();
    partial void OnintKilosChanging(int value);
    partial void OnintKilosChanged();
    partial void OnstrDescripcionChanging(string value);
    partial void OnstrDescripcionChanged();
    partial void OnintImporteChanging(int value);
    partial void OnintImporteChanged();
    partial void OnstrMetodoPagoChanging(string value);
    partial void OnstrMetodoPagoChanged();
    partial void OnstrlapsoChanging(string value);
    partial void OnstrlapsoChanged();
    partial void OnfkEmpleadoChanging(System.Nullable<int> value);
    partial void OnfkEmpleadoChanged();
    #endregion
		
		public tblVenta()
		{
			this._tblTotalVenta = new EntitySet<tblTotalVenta>(new Action<tblTotalVenta>(this.attach_tblTotalVenta), new Action<tblTotalVenta>(this.detach_tblTotalVenta));
			this._tblEmpleado = default(EntityRef<tblEmpleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int idVenta
		{
			get
			{
				return this._idVenta;
			}
			set
			{
				if ((this._idVenta != value))
				{
					this.OnidVentaChanging(value);
					this.SendPropertyChanging();
					this._idVenta = value;
					this.SendPropertyChanged("idVenta");
					this.OnidVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intBulto", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int intBulto
		{
			get
			{
				return this._intBulto;
			}
			set
			{
				if ((this._intBulto != value))
				{
					this.OnintBultoChanging(value);
					this.SendPropertyChanging();
					this._intBulto = value;
					this.SendPropertyChanged("intBulto");
					this.OnintBultoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intKilos", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int intKilos
		{
			get
			{
				return this._intKilos;
			}
			set
			{
				if ((this._intKilos != value))
				{
					this.OnintKilosChanging(value);
					this.SendPropertyChanging();
					this._intKilos = value;
					this.SendPropertyChanged("intKilos");
					this.OnintKilosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDescripcion", DbType="VarChar(250)", UpdateCheck=UpdateCheck.Never)]
		public string strDescripcion
		{
			get
			{
				return this._strDescripcion;
			}
			set
			{
				if ((this._strDescripcion != value))
				{
					this.OnstrDescripcionChanging(value);
					this.SendPropertyChanging();
					this._strDescripcion = value;
					this.SendPropertyChanged("strDescripcion");
					this.OnstrDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intImporte", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int intImporte
		{
			get
			{
				return this._intImporte;
			}
			set
			{
				if ((this._intImporte != value))
				{
					this.OnintImporteChanging(value);
					this.SendPropertyChanging();
					this._intImporte = value;
					this.SendPropertyChanged("intImporte");
					this.OnintImporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strMetodoPago", DbType="VarChar(150) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string strMetodoPago
		{
			get
			{
				return this._strMetodoPago;
			}
			set
			{
				if ((this._strMetodoPago != value))
				{
					this.OnstrMetodoPagoChanging(value);
					this.SendPropertyChanging();
					this._strMetodoPago = value;
					this.SendPropertyChanged("strMetodoPago");
					this.OnstrMetodoPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strlapso", DbType="VarChar(150)", UpdateCheck=UpdateCheck.Never)]
		public string strlapso
		{
			get
			{
				return this._strlapso;
			}
			set
			{
				if ((this._strlapso != value))
				{
					this.OnstrlapsoChanging(value);
					this.SendPropertyChanging();
					this._strlapso = value;
					this.SendPropertyChanged("strlapso");
					this.OnstrlapsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkEmpleado", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fkEmpleado
		{
			get
			{
				return this._fkEmpleado;
			}
			set
			{
				if ((this._fkEmpleado != value))
				{
					if (this._tblEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfkEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._fkEmpleado = value;
					this.SendPropertyChanged("fkEmpleado");
					this.OnfkEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVenta_tblTotalVenta", Storage="_tblTotalVenta", ThisKey="idVenta", OtherKey="fkVenta")]
		public EntitySet<tblTotalVenta> tblTotalVenta
		{
			get
			{
				return this._tblTotalVenta;
			}
			set
			{
				this._tblTotalVenta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblVenta", Storage="_tblEmpleado", ThisKey="fkEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
		public tblEmpleado tblEmpleado
		{
			get
			{
				return this._tblEmpleado.Entity;
			}
			set
			{
				tblEmpleado previousValue = this._tblEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._tblEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmpleado.Entity = null;
						previousValue.tblVenta.Remove(this);
					}
					this._tblEmpleado.Entity = value;
					if ((value != null))
					{
						value.tblVenta.Add(this);
						this._fkEmpleado = value.idEmpleado;
					}
					else
					{
						this._fkEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEmpleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTotalVenta(tblTotalVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblVenta = this;
		}
		
		private void detach_tblTotalVenta(tblTotalVenta entity)
		{
			this.SendPropertyChanging();
			entity.tblVenta = null;
		}
	}
}
#pragma warning restore 1591
