<?xml version="1.0" encoding="utf-8"?><Database Name="XIUGAR" Class="PaslumBaseDatoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=XIUGAR;Integrated Security=True" SettingsObjectName="Modelo.Properties.Settings" SettingsPropertyName="XIUGARConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAlmacen" Member="tblAlmacen">
    <Type Name="tblAlmacen">
      <Column Name="idAlmacen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="strDescripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intCapacidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkEncargado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblEmpleado_tblAlmacen" Member="tblEmpleado" ThisKey="fkEncargado" OtherKey="idEmpleado" Type="tblEmpleado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCliente" Member="tblCliente">
    <Type Name="tblCliente">
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strApellidoP" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strApellidoM" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strSituacionFiscal" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strCorreo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="strEntrega" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strHorario" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strMetodoPago" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fkDireccion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkTelefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkLogin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblDireccion_tblCliente" Member="tblDireccion" ThisKey="fkDireccion" OtherKey="idDireccion" Type="tblDireccion" IsForeignKey="true" />
      <Association Name="tblTelefono_tblCliente" Member="tblTelefono" ThisKey="fkTelefono" OtherKey="idTelefono" Type="tblTelefono" IsForeignKey="true" />
      <Association Name="tblUsuario_tblCliente" Member="tblUsuario" ThisKey="fkLogin" OtherKey="idUsuario" Type="tblUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDireccion" Member="tblDireccion">
    <Type Name="tblDireccion">
      <Column Name="idDireccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strColonia" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="strCalle" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="intCodpost" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="strNumInt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strNumExt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strReferencias" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="fkEstadoMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblDireccion_tblCliente" Member="tblCliente" ThisKey="idDireccion" OtherKey="fkDireccion" Type="tblCliente" />
      <Association Name="tblDireccion_tblEmpleado" Member="tblEmpleado" ThisKey="idDireccion" OtherKey="fkDireccion" Type="tblEmpleado" />
      <Association Name="tblEstado_Municipio_tblDireccion" Member="tblEstado_Municipio" ThisKey="fkEstadoMunicipio" OtherKey="idEstado_Municipio" Type="tblEstado_Municipio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblEmpleado" Member="tblEmpleado">
    <Type Name="tblEmpleado">
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strApellidoP" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strApellidoM" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strCorreo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="strSexo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strEdad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fkDireccion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkTelefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkLogin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblEmpleado_tblAlmacen" Member="tblAlmacen" ThisKey="idEmpleado" OtherKey="fkEncargado" Type="tblAlmacen" />
      <Association Name="tblEmpleado_tblVenta" Member="tblVenta" ThisKey="idEmpleado" OtherKey="fkEmpleado" Type="tblVenta" />
      <Association Name="tblDireccion_tblEmpleado" Member="tblDireccion" ThisKey="fkDireccion" OtherKey="idDireccion" Type="tblDireccion" IsForeignKey="true" />
      <Association Name="tblTelefono_tblEmpleado" Member="tblTelefono" ThisKey="fkTelefono" OtherKey="idTelefono" Type="tblTelefono" IsForeignKey="true" />
      <Association Name="tblUsuario_tblEmpleado" Member="tblUsuario" ThisKey="fkLogin" OtherKey="idUsuario" Type="tblUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblEstado" Member="tblEstado">
    <Type Name="tblEstado">
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strEstado" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="tblEstado_tblEstado_Municipio" Member="tblEstado_Municipio" ThisKey="idEstado" OtherKey="fkEstado" Type="tblEstado_Municipio" />
    </Type>
  </Table>
  <Table Name="dbo.tblEstado_Municipio" Member="tblEstado_Municipio">
    <Type Name="tblEstado_Municipio">
      <Column Name="idEstado_Municipio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fkEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkMunicipio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblEstado_Municipio_tblDireccion" Member="tblDireccion" ThisKey="idEstado_Municipio" OtherKey="fkEstadoMunicipio" Type="tblDireccion" />
      <Association Name="tblEstado_tblEstado_Municipio" Member="tblEstado" ThisKey="fkEstado" OtherKey="idEstado" Type="tblEstado" IsForeignKey="true" />
      <Association Name="TblMunicipio_tblEstado_Municipio" Member="TblMunicipio" ThisKey="fkMunicipio" OtherKey="idMunicipio" Type="TblMunicipio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblMunicipio" Member="TblMunicipio">
    <Type Name="TblMunicipio">
      <Column Name="idMunicipio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strMunicipio" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="TblMunicipio_tblEstado_Municipio" Member="tblEstado_Municipio" ThisKey="idMunicipio" OtherKey="fkMunicipio" Type="tblEstado_Municipio" />
    </Type>
  </Table>
  <Table Name="dbo.tblTelefono" Member="tblTelefono">
    <Type Name="tblTelefono">
      <Column Name="idTelefono" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCelular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strTelCasa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strOtro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblTelefono_tblCliente" Member="tblCliente" ThisKey="idTelefono" OtherKey="fkTelefono" Type="tblCliente" />
      <Association Name="tblTelefono_tblEmpleado" Member="tblEmpleado" ThisKey="idTelefono" OtherKey="fkTelefono" Type="tblEmpleado" />
    </Type>
  </Table>
  <Table Name="dbo.tblTotalVenta" Member="tblTotalVenta">
    <Type Name="tblTotalVenta">
      <Column Name="idTotalVenta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dblTotal" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Column Name="fkVenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblVenta_tblTotalVenta" Member="tblVenta" ThisKey="fkVenta" OtherKey="idVenta" Type="tblVenta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUsuario" Member="tblUsuario">
    <Type Name="tblUsuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strTipousuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tblUsuario_tblCliente" Member="tblCliente" ThisKey="idUsuario" OtherKey="fkLogin" Type="tblCliente" />
      <Association Name="tblUsuario_tblEmpleado" Member="tblEmpleado" ThisKey="idUsuario" OtherKey="fkLogin" Type="tblEmpleado" />
    </Type>
  </Table>
  <Table Name="dbo.tblVenta" Member="tblVenta">
    <Type Name="tblVenta">
      <Column Name="idVenta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="intBulto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intKilos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strDescripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intImporte" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strMetodoPago" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="strlapso" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="fkEmpleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblVenta_tblTotalVenta" Member="tblTotalVenta" ThisKey="idVenta" OtherKey="fkVenta" Type="tblTotalVenta" />
      <Association Name="tblEmpleado_tblVenta" Member="tblEmpleado" ThisKey="fkEmpleado" OtherKey="idEmpleado" Type="tblEmpleado" IsForeignKey="true" />
    </Type>
  </Table>
</Database>